# -*- mode: ruby -*-
# vi: set ft=ruby :
server_ip = "192.168.56.110"
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine314"
  config.ssh.insert_key = false
  config.vm.define "oel-ouarS", primary: true do |server|
    server.vm.network "private_network", ip: server_ip
    server.vm.hostname = "oel-ouarS"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	    vb.name = "oel-ouar"
      vb.cpus = "1"
    end
    server.vm.provision "shell", inline:<<-SHELL
      apk add curl
      export INSTALL_K3S_EXEC="--bind-address=#{server_ip} --flannel-iface=eth1"
      curl -sfL https://get.k3s.io | sh -
      echo "alias k='sudo kubectl'" > /home/vagrant/.bashrc && source /home/vagrant/.bashrc && chown vagrant:vagrant /home/vagrant/.bashrc
    SHELL
  end

end
